import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BgMusic from '../components/BgMusic/BgMusic'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Marco Sotola",
  description: "Generated by create Mira",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen`}>
        <div className="relative min-h-screen w-full bg-black">
          {/* Video de fondo */}
          <video
            autoPlay
            loop
            muted
            className="fixed top-0 left-0 w-full h-full object-cover z-0"
          >
            <source src="/videos/background-video.mp4" type="video/mp4" />
            Tu navegador no soporta el elemento video.
          </video>

          {/* Overlay opcional */}
          <div className="fixed top-0 left-0 w-full h-full bg-black/50 z-10"></div>

          {/* Contenido principal */}
          <div className="relative z-20 min-h-screen w-full flex text-white">
            <BgMusic />
            <main className="w-full p-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}